name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'custom workspace environment variable'
on: [push]
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: Print custom environment variables from ubuntu-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'custom step environment variable for Bash'
        run: |
          echo "Accessing environment variables using shell syntax"
          echo "1. $WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "2. $JOB_ENVIRONMENT_VARIABLE"
          echo "3. $STEP_ENVIRONMENT_VARIABLE"
          echo "4. $OVER_RIDE"
          echo "------------------------------------------------------"
          echo "Accessing environment variables using YAML syntax"
          echo "5. ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "6. ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "7. ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
          echo "8. ${{ env.OVER_RIDE }}"
  windows:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for windows'
    runs-on: windows-latest
    steps:
      - name: Print custom environment variables from windows-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'custom step environment variable for Powershell'
        run: |
          echo "Accessing environment variables using shell syntax"
          echo "1. $Env:WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "2. $Env:JOB_ENVIRONMENT_VARIABLE"
          echo "3. $Env:STEP_ENVIRONMENT_VARIABLE"
          echo "4. $Env:OVER_RIDE"
          echo "------------------------------------------------------"
          echo "Accessing environment variables using YAML syntax"
          echo "5. ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "6. ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "7. ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
          echo "8. ${{ env.OVER_RIDE }}"
